### ISSUE TITLE
Better name, 2nd try

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/klusolve#13]
Since most of the original code is rewritten and more features will be added, it's probably to rename the library/repo soon. I started calling it "KLUSolveX", but that's still bad. I was thinking about calling it `dss_...something` to follow the pattern.
One of planned features is adding more sparse solvers and related features. Maybe `dss_solve`?

**Comment by kdheepak** [comment]
How about `sparse_solve` or even `dss_sparse_solve`?

**Comment by PMeira** [comment]
`dss_sparse_solve` would be better than `klusolve` in general, yet there are some dense functions too.
Now, working on the loadshape code, maybe it would be better to merge this repo into dss_capi to simplify some things.

Let's wait some time before deciding, worst case we keep klusolvex since it's already in place.
