### ISSUE TITLE
Expose METIS

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/klusolve#8]
SuiteSparse already includes METIS. Since OpenDSS Version 8 needs it, it would be useful to include it for DSS C-API, since currently we don't package METIS at all.

METIS in a DLL would also remove the need to call the external executable and parse it's result, hence faster and more reliable to do in a multi-platform way.

**Comment by PMeira** [comment]
Since 4f37d21ea70a63ebcfc797f4759e2d2552949b64, METIS is now built along with KLU. Currently it builds some extra binaries from METIS.

The new `klusolve_metis` function still needs to be tested with DSS C-API and will be changed as required.

**Comment by kdheepak** [comment]
Awesome!
